---
kind: Service
apiVersion: v1
metadata:
  name: traffic-split
  namespace: istio-poc
  labels:
    app: traffic-split
spec:
  selector:
    app: traffic-split
  type: ClusterIP
  ports:
  - name: http
    port: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: traffic-split
  namespace: istio-poc
spec:
  hosts:
  - traffic-split.35.240.106.245.nip.io
  gateways:
  - istio-poc
  http:
  - name: traffic-split
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: traffic-split
        subset: v1
      weight: 80
    - destination:
        host: traffic-split
        subset: v2
      weight: 20
---