---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: traffic-split
  namespace: istio-poc
spec:
  host: traffic-split
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---