---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-split-v1
  namespace: istio-poc
  labels:
    app: traffic-split
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-split
  template:
    metadata:
      labels:
        app: traffic-split
        version: v1
    spec:
      containers:
      - name: traffic-split
        image: ichasco/test-app:v1
        imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-split-v2
  namespace: istio-poc
  labels:
    app: traffic-split
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-split
  template:
    metadata:
      labels:
        app: traffic-split
        version: v2
    spec:
      containers:
      - name: traffic-split
        image: ichasco/test-app:v2
        imagePullPolicy: Always
---