---
kind: Service
apiVersion: v1
metadata:
  name: traffic-rule
  namespace: istio-poc
  labels:
    app: traffic-rule
spec:
  selector:
    app: traffic-rule
  type: ClusterIP
  ports:
  - name: http
    port: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: traffic-rule
  namespace: istio-poc
spec:
  hosts:
    - traffic-rule.104.155.93.105.nip.io
  gateways:
    - istio-poc
  http:
    - match:
      - headers:
          user-agent:
            regex: '.*Firefox.*'
      route:
      - destination:
          host: traffic-rule
          subset: v1
    - match:
      - headers:
          user-agent:
            regex: '.*curl.*'
      route:
      - destination:
          host: traffic-rule
          subset: v2

---