---
kind: Service
apiVersion: v1
metadata:
  name: circuit-breaker
  namespace: istio-poc
  labels:
    app: circuit-breaker
spec:
  selector:
    app: circuit-breaker
  type: ClusterIP
  ports:
  - name: http
    port: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: circuit-breaker
  namespace: istio-poc
spec:
  hosts:
  - circuit-breaker.35.241.146.128.nip.io
  gateways:
  - istio-poc
  http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: circuit-breaker
        #   subset: v1
        # weight: 100
---