---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-rule-v1
  namespace: istio-poc
  labels:
    app: traffic-rule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-rule
  template:
    metadata:
      labels:
        app: traffic-rule
        version: v1
    spec:
      containers:
      - name: traffic-rule
        image: ichasco/test-app:v1
        imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-rule-v2
  namespace: istio-poc
  labels:
    app: traffic-rule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-rule
  template:
    metadata:
      labels:
        app: traffic-rule
        version: v2
    spec:
      containers:
      - name: traffic-rule
        image: ichasco/test-app:v2
        imagePullPolicy: Always
---