---
kind: Service
apiVersion: v1
metadata:
  name: traffic-mirror
  namespace: istio-poc
  labels:
    app: traffic-mirror
spec:
  selector:
    app: traffic-mirror
  type: ClusterIP
  ports:
  - name: http
    port: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: traffic-mirror
  namespace: istio-poc
spec:
  hosts:
  - traffic-mirror.104.155.93.105.nip.io
  gateways:
  - istio-poc
  http:
  - name: traffic-mirror
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: traffic-mirror
        subset: v1
      weight: 100
    mirror:
        host: traffic-mirror
        subset: v2
    mirror_percent: 100
---